### ISSUE TITLE
I keep getting this error when trying to install with mercury.

### ISSUE THREAD

**Issue by SuperCodeGuy** [Sledmine/coop-evolved#1]
Hello, sorry to be a bother but I keep getting this weird error when trying to install coop evolved with mercury:

![Screenshot 2023-02-09 214057](https://user-images.githubusercontent.com/122331973/218010254-ddd8d417-a4e1-4541-b7ca-ca4185420660.png)

I've looked around and no one seems to have a fix for this issue, I dunno what to do. I've run Mercury with admin permissions and ensured its game path is correct as well as reinstalling Custom Edition twice, got the 1.10 update as well and nothing works. Any ideas?

**Comment by Sledmine** [comment]
Hey, sorry for the late response I saw you in the Discord server and seems like you got this fixed :)

For the record this was caused due to some problems in our server configuration, we applied a fix for this on the last Friday night.
